### ISSUE TITLE
Should iconv be a requirement?

### ISSUE THREAD

**Issue by chrissound** [ddeboer/imap#115]
I've just run into the below error: 

```
PHP Fatal error:  Uncaught Ddeboer\Transcoder\Exception\ExtensionMissingException: iconv in /home/chris/Projects/Dashboard/vendor/ddeboer/transcoder/src/IconvTranscoder.php:16
Stack trace:
#0 /home/chris/Projects/Dashboard/vendor/ddeboer/transcoder/src/Transcoder.php(62): Ddeboer\Transcoder\IconvTranscoder->__construct('UTF-8')
#1 /home/chris/Projects/Dashboard/vendor/ddeboer/imap/src/Parameters.php(41): Ddeboer\Transcoder\Transcoder::create()
#2 /home/chris/Projects/Dashboard/vendor/ddeboer/imap/src/Parameters.php(20): Ddeboer\Imap\Parameters->decode('multipart_alter...')
#3 /home/chris/Projects/Dashboard/vendor/ddeboer/imap/src/Message/Part.php(236): Ddeboer\Imap\Parameters->add(Array)
#4 /home/chris/Projects/Dashboard/vendor/ddeboer/imap/src/Message.php(329): Ddeboer\Imap\Message\Part->parseStructure(Object(stdClass))
#5 /home/chris/Projects/Dashboard/vendor/ddeboer/imap/src/Message.php(34): Ddeboer\Imap\Message->loadStructure()
#6 /home/chris/Projects/Dashboard/vendor/ddeboer/imap/src/MessageIterator.php(29): Ddeboer\Imap\ in /home/chris/Projects/Dashboard/vendor/ddeboer/transcoder/src/IconvTranscoder.php on line 16
```

```
<?php
require "vendor/autoload.php";

use Ddeboer\Imap\Server;

$server = new Server('abc', 993);

$connection = $server->authenticate('abcxyz', 'abcxyz');

$inbox = $connection->getMailbox("INBOX");
$messages = $inbox->getMessages();

foreach ($messages as $message){
    echo $message->getSubject() . PHP_EOL;
}
```

**Comment by holdmann** [comment]
Obviously, yep :)

Transcoder requires either mb or iconv.

**Comment by ddeboer** [comment]
Indeed. @chrissound Does that answer your question?

**Comment by mate01988** [comment]
How to solve this error?

**Comment by chrissound** [comment]
Perhaps we could add these as dependencies to the composer.json? I see iconv is a dependency for require-dev only?

@mate01988 You need to install or enable the 'iconv' PHP extension.

**Comment by Slamdunk** [comment]
If we'll face the need to mark `iconv` as mandatory, it will be moved to `required` on this library or on its dependencies.

But first we need to stand strong charset test cases up.

**Comment by ddeboer** [comment]
Transcoding is not a responsibility of this library but of ddeboer/imap (a thin wrapper around mb/iconv) instead.

**Comment by Slamdunk** [comment]
Hi, the issue has been fixed in https://github.com/ddeboer/imap/pull/196 thank you for your feedback.
