### ISSUE TITLE
PHP Fatal error:  Uncaught Ddeboer\Imap\Exception\UnsupportedCharsetException

### ISSUE THREAD

**Issue by kuftachev** [ddeboer/imap#352]
PHP Fatal error:  Uncaught Ddeboer\Imap\Exception\UnsupportedCharsetException: [E_WARNING] Unsupported charset "windows-1252http-equivContent-Type": mb_convert_encoding(): Illegal character encoding specified
imap_alerts (0):
imap_errors (0): in /home/andrey/projects/current/imap/vendor/ddeboer/imap/src/Message/Transcoder.php:316
Stack trace:
#0 /home/andrey/projects/current/imap/vendor/ddeboer/imap/src/Message/Parameters.php(59): Ddeboer\Imap\Message\Transcoder::decode('Informaci\xF3n Ofe...', 'windows-1252htt...')
#1 /home/andrey/projects/current/imap/vendor/ddeboer/imap/src/Message/Headers.php(71): Ddeboer\Imap\Message\Parameters->decode('=?windows-1252h...')
#2 /home/andrey/projects/current/imap/vendor/ddeboer/imap/src/Message/Headers.php(25): Ddeboer\Imap\Message\Headers->parseHeader('subject', '=?windows-1252h...')
#3 /home/andrey/projects/current/imap/vendor/ddeboer/imap/src/Message.php(155): Ddeboer\Imap\Message\Headers->__construct(Array)
#4 /home/andrey/projects/current/imap/vendor/ddeboer/imap/src/Message/AbstractMe in /home/andrey/projects/current/imap/vendor/ddeboer/imap/src/Message/Transcoder.php on line 316

**Comment by Slamdunk** [comment]
`windows-1252http-equivContent-Type` is not a charset, the email structure you are fetching is messed up: `Content-Type` is a tag and should not be part of the charset one.
