### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by zorro1199** [ddeboer/imap#481]
Hello,

After upgrading from PHP 7.4 to PHP 8.0, the library stopped working for me and I'm not able to retrieve message numbers using `getNumber()` any longer.

Here's my code:

```
$server = new Server(EMAIL_SERVER, EMAIL_PORT, EMAIL_FLAG);
$connection = $server->authenticate(EMAIL_USERNAME, EMAIL_PASSWORD);
$mailbox = $connection->getMailbox(EMAIL_MAILBOX);
$search = new SearchExpression();
$messages = $mailbox->getMessages($search, \SORTDATE, true);
foreach ($messages as $message) {
	$messageNumber = $message->getNumber();
}
```

Here comes the stack trace:
```
Ddeboer\Imap\Exception\MessageDoesNotExistException: Message "12345" does not exist
imap_alerts (0):
imap_errors (0): in C:\XXX\ddeboer\vendor\ddeboer\imap\src\Message.php:119
Stack trace:
#0 C:\XXX\ddeboer\vendor\ddeboer\imap\src\Message\AbstractPart.php(163): Ddeboer\Imap\Message->assertMessageExists()
#1 C:\XXX\test.php(42): Ddeboer\Imap\Message\AbstractPart->getNumber()
#2 {main}
```

Can you please upgrade the library so it gets compatible with PHP 8?

Thank you so much in advance.

Best,

Ben

**Comment by Slamdunk** [comment]
Released in [1.11.0](https://github.com/ddeboer/imap/releases/tag/1.11.0)
