### ISSUE TITLE
PHP Fatal error Failed to parse time string in ddeboer/imap/src/Message.php

### ISSUE THREAD

**Issue by skynet** [ddeboer/imap#89]
```
Exception detected at line 385 in /var/www/app/test.php :
exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (Fri, 24 Jul 2015 20:36:59 -0-100 -0700) at position 33 (-): Double timezone specification' in /var/www/app/vendor/ddeboer/imap/src/Message/Headers.php:56
Stack trace:
#0 /var/www/app/vendor/ddeboer/imap/src/Message/Headers.php(56): DateTime->__construct('Fri, 24 Jul 201...')
#1 /var/www/app/vendor/ddeboer/imap/src/Message/Headers.php(23): Ddeboer\Imap\Message\Headers->parseHeader('date', 'Fri, 24 Jul 201...')
#2 /var/www/app/vendor/ddeboer/imap/src/Message.php(185): Ddeboer\Imap\Message\Headers->__construct(Object(stdClass))
#3 /var/www/app/vendor/ddeboer/imap/src/Message.php(56): Ddeboer\Imap\Message->getHeaders()
#4 /var/www/app/vendor/emailapi/inboxwatch/src/InboxWatch.php(383): Ddeboer\Imap\Message->getFrom()
#5 /var/www/app/test.php(44): MyApp->imap_retrieve()
```

**Comment by Slamdunk** [comment]
That seems an invalid Date header: can you provide the raw message headers?

**Comment by Slamdunk** [comment]
Dates are now extensively tested:
https://github.com/ddeboer/imap/blob/6ae87c943a7ccd443211f9aadd99d8f8de624dd3/tests/MessageTest.php#L320-L330
If you'll ever encounter this message again please ping me.

Still, now you can catch invalid date header with `InvalidDateHeaderException`: https://github.com/ddeboer/imap/pull/205

Thank you for your feedback.
